// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bounded_regression_cpp
List bounded_regression_cpp(const Environment& dataModel, const bool& intercept, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_bounded_regression_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(bounded_regression_cpp(dataModel, intercept, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// FusedLasso_cpp
List FusedLasso_cpp(const Environment& dataModel, const bool& intercept, const List& regParam, const List& controlFit);
RcppExport SEXP _quadrupen_FusedLasso_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP regParamSEXP, SEXP controlFitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type controlFit(controlFitSEXP);
    rcpp_result_gen = Rcpp::wrap(FusedLasso_cpp(dataModel, intercept, regParam, controlFit));
    return rcpp_result_gen;
END_RCPP
}
// group_lava_l1l2_dense_cpp
List group_lava_l1l2_dense_cpp(const Environment& dataModel, const bool& intercept, const arma::uvec& group, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_group_lava_l1l2_dense_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP groupSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(group_lava_l1l2_dense_cpp(dataModel, intercept, group, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// group_lava_l1linf_dense_cpp
List group_lava_l1linf_dense_cpp(const Environment& dataModel, const bool& intercept, const arma::uvec& group, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_group_lava_l1linf_dense_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP groupSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(group_lava_l1linf_dense_cpp(dataModel, intercept, group, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// group_lava_coop_dense_cpp
List group_lava_coop_dense_cpp(const Environment& dataModel, const bool& intercept, const arma::uvec& group, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_group_lava_coop_dense_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP groupSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(group_lava_coop_dense_cpp(dataModel, intercept, group, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// group_enet_l1l2_dense_cpp
List group_enet_l1l2_dense_cpp(const Environment& dataModel, const bool& intercept, const arma::uvec& group, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_group_enet_l1l2_dense_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP groupSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(group_enet_l1l2_dense_cpp(dataModel, intercept, group, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// group_enet_l1l2_sparse_cpp
List group_enet_l1l2_sparse_cpp(const Environment& dataModel, const bool& intercept, const arma::uvec& group, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_group_enet_l1l2_sparse_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP groupSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(group_enet_l1l2_sparse_cpp(dataModel, intercept, group, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// group_enet_l1linf_dense_cpp
List group_enet_l1linf_dense_cpp(const Environment& dataModel, const bool& intercept, const arma::uvec& group, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_group_enet_l1linf_dense_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP groupSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(group_enet_l1linf_dense_cpp(dataModel, intercept, group, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// group_enet_l1linf_sparse_cpp
List group_enet_l1linf_sparse_cpp(const Environment& dataModel, const bool& intercept, const arma::uvec& group, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_group_enet_l1linf_sparse_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP groupSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(group_enet_l1linf_sparse_cpp(dataModel, intercept, group, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// group_enet_coop_dense_cpp
List group_enet_coop_dense_cpp(const Environment& dataModel, const bool& intercept, const arma::uvec& group, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_group_enet_coop_dense_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP groupSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(group_enet_coop_dense_cpp(dataModel, intercept, group, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// group_enet_coop_sparse_cpp
List group_enet_coop_sparse_cpp(const Environment& dataModel, const bool& intercept, const arma::uvec& group, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_group_enet_coop_sparse_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP groupSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(group_enet_coop_sparse_cpp(dataModel, intercept, group, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// lava_dense_cpp
List lava_dense_cpp(const Environment& dataModel, const bool& intercept, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_lava_dense_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(lava_dense_cpp(dataModel, intercept, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// ridge_cpp
List ridge_cpp(const Environment& dataModel, const bool& intercept, const List& regParam, const List& controlFit);
RcppExport SEXP _quadrupen_ridge_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP regParamSEXP, SEXP controlFitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type controlFit(controlFitSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_cpp(dataModel, intercept, regParam, controlFit));
    return rcpp_result_gen;
END_RCPP
}
// elastic_net_dense_cpp
List elastic_net_dense_cpp(const Environment& dataModel, const bool& intercept, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_elastic_net_dense_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(elastic_net_dense_cpp(dataModel, intercept, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// elastic_net_sparse_cpp
List elastic_net_sparse_cpp(const Environment& dataModel, const bool& intercept, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_elastic_net_sparse_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(elastic_net_sparse_cpp(dataModel, intercept, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// mcp_dense_cpp
List mcp_dense_cpp(const Environment& dataModel, const bool& intercept, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_mcp_dense_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(mcp_dense_cpp(dataModel, intercept, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// mcp_sparse_cpp
List mcp_sparse_cpp(const Environment& dataModel, const bool& intercept, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_mcp_sparse_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(mcp_sparse_cpp(dataModel, intercept, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// scad_dense_cpp
List scad_dense_cpp(const Environment& dataModel, const bool& intercept, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_scad_dense_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(scad_dense_cpp(dataModel, intercept, regParam, control));
    return rcpp_result_gen;
END_RCPP
}
// scad_sparse_cpp
List scad_sparse_cpp(const Environment& dataModel, const bool& intercept, const List& regParam, const List& control);
RcppExport SEXP _quadrupen_scad_sparse_cpp(SEXP dataModelSEXP, SEXP interceptSEXP, SEXP regParamSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Environment& >::type dataModel(dataModelSEXP);
    Rcpp::traits::input_parameter< const bool& >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< const List& >::type regParam(regParamSEXP);
    Rcpp::traits::input_parameter< const List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(scad_sparse_cpp(dataModel, intercept, regParam, control));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_quadrupen_bounded_regression_cpp", (DL_FUNC) &_quadrupen_bounded_regression_cpp, 4},
    {"_quadrupen_FusedLasso_cpp", (DL_FUNC) &_quadrupen_FusedLasso_cpp, 4},
    {"_quadrupen_group_lava_l1l2_dense_cpp", (DL_FUNC) &_quadrupen_group_lava_l1l2_dense_cpp, 5},
    {"_quadrupen_group_lava_l1linf_dense_cpp", (DL_FUNC) &_quadrupen_group_lava_l1linf_dense_cpp, 5},
    {"_quadrupen_group_lava_coop_dense_cpp", (DL_FUNC) &_quadrupen_group_lava_coop_dense_cpp, 5},
    {"_quadrupen_group_enet_l1l2_dense_cpp", (DL_FUNC) &_quadrupen_group_enet_l1l2_dense_cpp, 5},
    {"_quadrupen_group_enet_l1l2_sparse_cpp", (DL_FUNC) &_quadrupen_group_enet_l1l2_sparse_cpp, 5},
    {"_quadrupen_group_enet_l1linf_dense_cpp", (DL_FUNC) &_quadrupen_group_enet_l1linf_dense_cpp, 5},
    {"_quadrupen_group_enet_l1linf_sparse_cpp", (DL_FUNC) &_quadrupen_group_enet_l1linf_sparse_cpp, 5},
    {"_quadrupen_group_enet_coop_dense_cpp", (DL_FUNC) &_quadrupen_group_enet_coop_dense_cpp, 5},
    {"_quadrupen_group_enet_coop_sparse_cpp", (DL_FUNC) &_quadrupen_group_enet_coop_sparse_cpp, 5},
    {"_quadrupen_lava_dense_cpp", (DL_FUNC) &_quadrupen_lava_dense_cpp, 4},
    {"_quadrupen_ridge_cpp", (DL_FUNC) &_quadrupen_ridge_cpp, 4},
    {"_quadrupen_elastic_net_dense_cpp", (DL_FUNC) &_quadrupen_elastic_net_dense_cpp, 4},
    {"_quadrupen_elastic_net_sparse_cpp", (DL_FUNC) &_quadrupen_elastic_net_sparse_cpp, 4},
    {"_quadrupen_mcp_dense_cpp", (DL_FUNC) &_quadrupen_mcp_dense_cpp, 4},
    {"_quadrupen_mcp_sparse_cpp", (DL_FUNC) &_quadrupen_mcp_sparse_cpp, 4},
    {"_quadrupen_scad_dense_cpp", (DL_FUNC) &_quadrupen_scad_dense_cpp, 4},
    {"_quadrupen_scad_sparse_cpp", (DL_FUNC) &_quadrupen_scad_sparse_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_quadrupen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
