# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bounded_regression_cpp <- function(dataModel, intercept, regParam, control) {
    .Call(`_quadrupen_bounded_regression_cpp`, dataModel, intercept, regParam, control)
}

FusedLasso_cpp <- function(dataModel, intercept, regParam, controlFit) {
    .Call(`_quadrupen_FusedLasso_cpp`, dataModel, intercept, regParam, controlFit)
}

group_lava_l1l2_dense_cpp <- function(dataModel, intercept, group, regParam, control) {
    .Call(`_quadrupen_group_lava_l1l2_dense_cpp`, dataModel, intercept, group, regParam, control)
}

group_lava_l1linf_dense_cpp <- function(dataModel, intercept, group, regParam, control) {
    .Call(`_quadrupen_group_lava_l1linf_dense_cpp`, dataModel, intercept, group, regParam, control)
}

group_lava_coop_dense_cpp <- function(dataModel, intercept, group, regParam, control) {
    .Call(`_quadrupen_group_lava_coop_dense_cpp`, dataModel, intercept, group, regParam, control)
}

group_enet_l1l2_dense_cpp <- function(dataModel, intercept, group, regParam, control) {
    .Call(`_quadrupen_group_enet_l1l2_dense_cpp`, dataModel, intercept, group, regParam, control)
}

group_enet_l1l2_sparse_cpp <- function(dataModel, intercept, group, regParam, control) {
    .Call(`_quadrupen_group_enet_l1l2_sparse_cpp`, dataModel, intercept, group, regParam, control)
}

group_enet_l1linf_dense_cpp <- function(dataModel, intercept, group, regParam, control) {
    .Call(`_quadrupen_group_enet_l1linf_dense_cpp`, dataModel, intercept, group, regParam, control)
}

group_enet_l1linf_sparse_cpp <- function(dataModel, intercept, group, regParam, control) {
    .Call(`_quadrupen_group_enet_l1linf_sparse_cpp`, dataModel, intercept, group, regParam, control)
}

group_enet_coop_dense_cpp <- function(dataModel, intercept, group, regParam, control) {
    .Call(`_quadrupen_group_enet_coop_dense_cpp`, dataModel, intercept, group, regParam, control)
}

group_enet_coop_sparse_cpp <- function(dataModel, intercept, group, regParam, control) {
    .Call(`_quadrupen_group_enet_coop_sparse_cpp`, dataModel, intercept, group, regParam, control)
}

lava_dense_cpp <- function(dataModel, intercept, regParam, control) {
    .Call(`_quadrupen_lava_dense_cpp`, dataModel, intercept, regParam, control)
}

ridge_cpp <- function(dataModel, intercept, regParam, controlFit) {
    .Call(`_quadrupen_ridge_cpp`, dataModel, intercept, regParam, controlFit)
}

elastic_net_dense_cpp <- function(dataModel, intercept, regParam, control) {
    .Call(`_quadrupen_elastic_net_dense_cpp`, dataModel, intercept, regParam, control)
}

elastic_net_sparse_cpp <- function(dataModel, intercept, regParam, control) {
    .Call(`_quadrupen_elastic_net_sparse_cpp`, dataModel, intercept, regParam, control)
}

mcp_dense_cpp <- function(dataModel, intercept, regParam, control) {
    .Call(`_quadrupen_mcp_dense_cpp`, dataModel, intercept, regParam, control)
}

mcp_sparse_cpp <- function(dataModel, intercept, regParam, control) {
    .Call(`_quadrupen_mcp_sparse_cpp`, dataModel, intercept, regParam, control)
}

scad_dense_cpp <- function(dataModel, intercept, regParam, control) {
    .Call(`_quadrupen_scad_dense_cpp`, dataModel, intercept, regParam, control)
}

scad_sparse_cpp <- function(dataModel, intercept, regParam, control) {
    .Call(`_quadrupen_scad_sparse_cpp`, dataModel, intercept, regParam, control)
}

